{
 "title": "Home",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Importing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Parallel Importers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "count(sum by (pod)(tenants_added_total))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time to add tenants",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(tenant_batch_seconds_sum[$__rate_interval]))/sum(rate(tenant_batch_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Batch Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(objects_batch_seconds_sum[$__rate_interval]))/sum(rate(objects_batch_seconds_count[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Importing ",
     "type": "text",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
     "options": {
      "content": "# Import Metrics\n\nAll import metrics are obtained client-side from the parallel import scripts. They are summed across parallel import pods."
     }
    },
    {
     "title": "Weaviate Tenants ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 25 },
     "targets": [
      { "expr": "sum(tenants_added_total)", "legendFormat": "__auto" },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Weaviate Objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 25 },
     "targets": [
      { "expr": "sum(objects_added_total)", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "Querying", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "QPS (avg over 30s sliding window)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(vector_query_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean QPS ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_query_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(query_result_total{result=\"success\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(query_result_total{result=\"failure\"}[$__rate_interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Query success rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(query_result_total{result=\"success\"}[$__range]))/sum(rate(query_result_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently active users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(querying_users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(querying_users_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ready Weaviate Pods",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=~\"weaviate.*\",condition=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Weaviate pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{pod=~\"weaviate.*\",condition=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Query latency ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(vector_query_seconds_sum[$__rate_interval]))/sum(rate(vector_query_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Query latency ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_query_seconds_sum[$__rate_interval]))/sum(rate(vector_query_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}