{
 "title": "Schema Txs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Tx Durations across all nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(schema_tx_duration_seconds_sum{status=\"commit\"}[$__rate_interval]))/sum(rate(schema_tx_duration_seconds_count{status=\"commit\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(schema_tx_duration_seconds_sum{status=\"close_read\"}[$__rate_interval]))/sum(rate(schema_tx_duration_seconds_count{status=\"close_read\"}[$__rate_interval]))",
     "legendFormat": "read tx"
    },
    {
     "expr": "sum(rate(schema_tx_duration_seconds_sum{status=\"abort\"}[$__rate_interval]))/sum(rate(schema_tx_duration_seconds_count{status=\"abort\"}[$__rate_interval]))",
     "legendFormat": "aborted"
    }
   ]
  },
  {
   "title": "Tx Durations across all nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(schema_tx_opened_total{ownership=\"coordinator\"}[$__rate_interval]))",
     "legendFormat": "opened-coordinator"
    },
    {
     "expr": "sum(rate(schema_tx_closed_total{ownership=\"coordinator\"}[$__rate_interval]))",
     "legendFormat": "closed-coordinator"
    },
    {
     "expr": "sum(rate(schema_tx_opened_total{ownership=\"participant\"}[$__rate_interval]))",
     "legendFormat": "opened-participant"
    },
    {
     "expr": "sum(rate(schema_tx_closed_total{ownership=\"participant\"}[$__rate_interval]))",
     "legendFormat": "closed-participant"
    },
    {
     "expr": "sum(rate(schema_tx_closed_total{status=\"expire\"}[$__rate_interval]))",
     "legendFormat": "expired"
    }
   ]
  },
  {
   "title": "Total unclosed TX",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(schema_tx_opened_total)-sum(schema_tx_closed_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Durations of coordinating nodes (Successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(schema_tx_duration_seconds_sum{status=\"commit\",ownership=\"coordinator\"}[$__rate_interval])/rate(schema_tx_duration_seconds_count{status=\"commit\",ownership=\"coordinator\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{ownership}}"
    }
   ]
  },
  {
   "title": "Tx Durations of coordinating nodes (Aborted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(schema_tx_duration_seconds_sum{status=\"abort\",ownership=\"coordinator\"}[$__rate_interval])/rate(schema_tx_duration_seconds_count{status=\"abort\",ownership=\"coordinator\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{ownership}}"
    }
   ]
  },
  {
   "title": "Tx Durations of participating nodes (Successful)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(schema_tx_duration_seconds_sum{status=\"commit\",ownership=\"participant\"}[$__rate_interval])/rate(schema_tx_duration_seconds_count{status=\"commit\",ownership=\"participant\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{ownership}}"
    }
   ]
  },
  {
   "title": "Tx Durations of participating nodes (Aborted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(schema_tx_duration_seconds_sum{status=\"abort\",ownership=\"participant\"}[$__rate_interval])/rate(schema_tx_duration_seconds_count{status=\"abort\",ownership=\"participant\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{ownership}}"
    }
   ]
  }
 ]
}