apiVersion: batch/v1
kind: Job
metadata:
  name: importer
  namespace: "$K8S_NAMESPACE"
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - client-pool 

      containers:
      - image: "gcr.io/semi-automated-benchmarking/load-test-importer:$GIT_HASH"
        name: schema-resetter
        command: ["python3", "reset_schema.py"]
        imagePullPolicy: Always
        env:
        - name: "HOST"
          value: "weaviate.$K8S_NAMESPACE.svc.cluster.local"
        - name: "HOST_GRPC"
          value: "weaviate-grpc.$K8S_NAMESPACE.svc.cluster.local"
        - name: "REPLICATION_FACTOR"
          value: "$REPLICATION_FACTOR"
      restartPolicy: Never
  backoffLimit: 4
